### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Idriel** [msteinert/pam#26]
Hi,

I am trying to test this simple code

```
package main

import (
	"errors"
	"fmt"
	"os"
	"os/user"

	"github.com/msteinert/pam/v2"
)

type Credentials struct {
	User     string
	Password string
}

func (c Credentials) RespondPAM(s pam.Style, msg string) (string, error) {
	switch s {
	case pam.PromptEchoOn:
		return c.User, nil
	case pam.PromptEchoOff:
		return c.Password, nil
	}
	return "", errors.New("unexpected")
}

func main() {
	u, _ := user.Current()
	c := Credentials{
		// the custom service only cares about correct user name.
		Password: "wrongsecret",
	}

	t, err := pam.StartConfDir("permit-service", u.Username, c, "test-services")
	defer func() {
		if t != nil {
			_ = t.End()
		}
	}()

	if !pam.CheckPamHasStartConfdir() {
		if err == nil {
			fmt.Printf("start should have errored out as pam_start_confdir is not available: %v", err)
		}
		// nothing else we do, we don't support it.
		return
	}
	//	service, _ := t.GetItem(pam.Service)
	//	fmt.Printf("Service: %s", service)

	err = t.Authenticate(0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "authenticate: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("authentication succeeded!")
}
```

But I am getting following error when running
```
go run *.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4993f3]

goroutine 1 [running]:
github.com/msteinert/pam/v2.(*Transaction).Authenticate.func1(0xc00006ee70?, 0x0)
        /home/user/go/pkg/mod/github.com/msteinert/pam/v2@v2.0.0/transaction.go:319 +0x13
github.com/msteinert/pam/v2.(*Transaction).Authenticate(0x0, 0xe?)
        /home/user/go/pkg/mod/github.com/msteinert/pam/v2@v2.0.0/transaction.go:319 +0x18
main.main()
        /home/user/pam-test/main.go:51 +0x17c
exit status 2
```

**Comment by Idriel** [comment]
I forgot to create test-services and permit-service dir
